### ISSUE TITLE
Preslection

### ISSUE THREAD

**Issue by 1-alex98** [Rackover/FAF-VotingMachine#3]
3. There should not be "downlord" preselected that makes people vote for downlord(as they are too lazy to change preselection). Anyway you can also have no votingAnwser with alternativeOrdinal 0, so it would be totally fine to set it to "-"

![image 4](https://user-images.githubusercontent.com/19996713/40887071-1a9d8a88-6743-11e8-9109-42ac551c703f.png)

**Comment by louvenarde** [comment]
Fixed in 23d6629f14ded4657bee4ab37dd0988f7131d376
