### ISSUE TITLE
Alternative multi choices

### ISSUE THREAD

**Issue by 1-alex98** [Rackover/FAF-VotingMachine#4]
5. Pay attention, I just realized the bug i fixed will affect you. It had to do with alternativeOrdinal validation. So the api accepted you sending any ordinals till now, but now it will only accept votes where the alternativeOrdinals of votinganswers for one question go like 0,1,2,3...
0,1,2,2 will be rejected and 2,3 , 1,2,3 , 0,2,3 as well (bearbeitet)

No voting answers are ok as well and everything that is continous (bearbeitet)
So no clue what happens if you have 3 votinganswers to give, if you have 3 boxes where you can select "downlord" then "-" and then "axel12" that would be fatal

I would disable choice boxes of 2nd and 3rd choice till the user selected something that is not "-" of the first choice

**Comment by louvenarde** [comment]
Fixed in dc5371289e4a155066714c96344807e49912e5b8
