### ISSUE TITLE
leaving out a choice in between

### ISSUE THREAD

**Issue by 1-alex98** [Rackover/FAF-VotingMachine#7]
That should not be possible....
![image](https://user-images.githubusercontent.com/19996713/40889728-16325040-676c-11e8-9f2f-87eca7435999.png)

**Comment by 1-alex98** [comment]
Api will reject this

**Comment by louvenarde** [comment]
Form is rejecting this on submit already. That's why I closed the issue for now.

**Comment by louvenarde** [comment]
https://github.com/Rackover/FAF-VotingMachine/blob/master/public/vote.html#L168

**Comment by 1-alex98** [comment]
ok
